language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
    - php: 7.0
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.1
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
    - php: 7.1
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.1
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.2
      env: LARAVEL='5.4.*' TESTBENCH='3.4.*'
    - php: 7.2
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.2
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*' COVERAGE=1

before_install:
  - travis_retry composer self-update
  - travis_retry composer require --no-update --no-interaction "illuminate/database:${LARAVEL}" "illuminate/support:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"

install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist $COMPOSER_ARGS

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - if [[ $COVERAGE = '1' ]]; then
      travis_retry composer require php-coveralls/php-coveralls
      travis_retry php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
    fi
